@startuml c4_contexto_nivel1

!include  https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

'LAYOUT_WITH_LEGEND()

title Diagrama de Contexto (Nível 1) - Sistema de Gestão de Atendimentos SAMU

' =========================
' Pessoas
' =========================

Person(admin, "Administrador", "Gerencia usuários, unidades, relatórios e métricas do sistema.")

Person(enfermeiro, "Enfermeiro/Técnico", "Realiza o registro digital dos atendimentos e consulta informações.")

System(sistema_samu, "Sistema de Gestão SAMU","Sistema responsável pelo registro digital de atendimentos, autenticação de usuários, funcionamento offline, sincronização de dados, geração de relatórios e monitoramento operacional.")

' =========================
' Sistemas Externos
' =========================

System_Ext(prefeitura, "Banco da Prefeitura","Armazena dados integrados dos atendimentos e registros municipais.")

System_Ext(gps, "Serviço de GPS", "Fornece localização automática das ocorrências.")

System_Ext(pdf, "Serviço de Exportação PDF","Responsável pela geração e exportação de relatórios em PDF.")

' =========================
' Relacionamentos
' =========================

Rel(admin, sistema_samu, "Gerencia usuários, unidades, dashboards,relatórios e métricas")

Rel(enfermeiro, sistema_samu, "Registra atendimentos, consulta fichas e utiliza funcionalidades offline") 

Rel(sistema_samu, prefeitura, "Sincroniza dados dos atendimentos e registros das unidades", "HTTPS/API")

Rel(sistema_samu, gps, "Obtém localização automática do atendimento","GPS")

Rel(sistema_samu, pdf, "Gera e exporta relatórios em PDF")

' =========================
' Legenda Complementar
' =========================

SHOW_LEGEND()
@enduml

